### ISSUE TITLE
Break down big classes to smaller classes

### ISSUE THREAD

**Issue by coderhs** [werner/crystal_on_steroids#7]
With each addition of new features the size of the single class is increasing. May I suggest we break up a class in the following format.

```
+-- arrays/
|   +-- grouping/
|         +-- in_groups.cr
|         +-- split.cr
|   +-- grouping.cr
```

So that the code will be more organised. If people want to just include the grouping of array they can do `crystal_on_steroids/arrays/grouping` or if the one just a specific method they can do `crystal_on_steroids/arrays/grouping/in_groups`.

The above require is just an added benefit the main thing is to make the code more organised as we are going to add more methods.

**Comment by werner** [comment]
I think this might be a good idea. I'm not sure how big array.cr could be, but I think by now is good.

**Comment by werner** [comment]
Fix in https://github.com/werner/crystal_on_steroids/releases/tag/v0.11.0
